config/routes.rb
ClockIn::Application.routes.draw do

  resources :users do
    resources :clock_times
  end

  match '/users/:user_id/auto_clock_out', :to => 'users#auto_clock_out', :as => 'auto_clock_out_user'

  match '/users/:user_id/auto_clock_in', :to => 'users#auto_clock_in', :as => 'auto_clock_in_user'

  root :to => "users#index"

end

app/models/clock_time.rb
class ClockTime
  include Mongoid::Document
  field :in, :type => Time
  field :out, :type => Time

  embedded_in :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :password, :type => String
  field :email, :type => String
  field :_id, :type => String

  embeds_many :clock_times
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clock_times_controller.rb
class ClockTimesController < ApplicationController
  # GET /clock_times
  # GET /clock_times.json
  def index
    @clock_times = ClockTime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clock_times }
    end
  end

  # GET /clock_times/1
  # GET /clock_times/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clock_time }
    end
  end

  # GET /clock_times/new
  # GET /clock_times/new.json
  def new
    @user = User.find(params[:user_id])
    @clock_time = @user.clock_times.new(:in => Time.now)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clock_time }
    end
  end

  # GET /clock_times/1/edit
  def edit
    @user = User.find(params[:user_id])
    @clock_time = @user.clock_times.find(params[:id])

    @clocking_out = params[:clock_out]
  end

  # POST /clock_times
  # POST /clock_times.json
  def create
    @user = User.find(params[:user_id])
    @clock_time = @user.clock_times.new(params[:clock_time])

    time_in_to_update = get_time_to_update(params["use_current"], params[:clock_time], "in")


    @clock_time.in = time_in_to_update

    respond_to do |format|
      if @clock_time.save
        format.html { redirect_to @user, notice: 'You have successfully clocked in' }
        format.json { render json: @clock_time, status: :created, location: @clock_time }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @clock_time.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /clock_times/1
  # PUT /clock_times/1.json
  def update
    @user = User.find(params[:user_id])
    @clock_time = @user.clock_times.find(params[:id])

    time_in_to_update = get_time_to_update(params["use_current"], params[:clock_time], "in")

    @clock_time.in = time_in_to_update

    time_out_to_update = get_time_to_update(params["use_current_out"], params[:clock_time], "out")

    if !time_out_to_update.nil?
      @clock_time.out = time_out_to_update
    end

    respond_to do |format|
      if @clock_time.update_attributes(params[:clock_time])
        format.html { redirect_to @user, notice: 'Your clock in time was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clock_time.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_time_to_update(use_current, clock_time, which)
    if use_current == 'true'
      return Time.now
    else
      if clock_time[which + "(1i)"].present?
        return Time.parse(clock_time[which + "(1i)"].to_s + "-" + clock_time[which + "(2i)"].to_s + "-" +
                              clock_time[which + "(3i)"].to_s + " " + clock_time[which + "(4i)"].to_s + ":" + clock_time[which + "(5i)"].to_s)
      else
        return nil
      end
    end
  end

  # DELETE /clock_times/1
  # DELETE /clock_times/1.json
  def destroy
    @user = User.find(params[:user_id])
    @clock_time = @user.clock_times.find(params[:id])
    @clock_time.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.js {render json: @clock_time, content_type: 'text/json' }
    end


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1DIS
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    @clock_times = @user.clock_times.all
    @clock_times_by_week = separate_by_weeks @clock_times
    puts "farg..." + @clock_times_by_week.inspect
    @clock_time = @user.clock_times.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def separate_by_weeks clock_times
    week_hash = Hash.new {|hash,key| hash[key] = [] }

    for clock_time in clock_times
      week_hash[clock_time.in.strftime("%Y-%U")].push clock_time
    end

    week_hash
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    params[:user]["_id"] = params[:user][:name]
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save()
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy


    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
      puts "*************:" + @user.inspect
      format.js { render nothing: true }
    end
  end

  def auto_clock_in
    @user = User.find(params[:user_id])

    @clock_times = @user.clock_times.all

    @already_clocked_in = is_user_already_clocked_in @clock_times



    if @already_clocked_in
      redirect_to @user, notice: 'You have already clocked in, and cannot again until you clock out'
    else
      @clock_time = @user.clock_times.new(:in => Time.now)

      respond_to do |format|
        if @clock_time.save
          format.html { redirect_to @user, notice: 'You have successfully clocked in' }
          format.json { render json: @clock_time, status: :created, location: @clock_time }
        else
          format.html { render action: "new" }
          format.json { render json: @clock_time.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  def is_user_already_clocked_in clock_times
    already_clocked_in = false

    for clock_time in clock_times
      if clock_time.out.nil?
        already_clocked_in = true
      end
    end

    already_clocked_in
  end

  def get_last_clocked_in_clock_time clock_times
    for clock_time in clock_times
      if clock_time.out.nil?
        break
      end
      clock_time = nil
    end

    clock_time
  end

  def auto_clock_out
    @user = User.find(params[:user_id])

    puts @user.inspect


    @clock_times = @user.clock_times.all

    @last_clock_time = get_last_clocked_in_clock_time @clock_times

    if !@last_clock_time.nil?
      @clock_time = @user.clock_times.find(@last_clock_time.id)

      respond_to do |format|
        if @clock_time.update_attributes(:out => Time.now)
          format.html { redirect_to @user, notice: 'You were successfully clocked out.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @clock_time.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @user, notice: "You cannot clock out, since you haven't been clocked in yet"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clock_times_helper.rb
module ClockTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clock_times/_form.html.erb
<%= form_for [@user, @clock_time], :remote => true do |f| %>
    <% if @clock_time.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@clock_time.errors.count, "error") %> prohibited this clock_time from being saved:</h2>

          <ul>
            <% @clock_time.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <script type="text/javascript">
        $(document).ready(function () {
            toggle_hidden('#datetime_select', '#use_current', '#use_current_time');
            toggle_hidden('#datetime_select_out', '#use_current_out', '#use_current_time_out');
        });
    </script>

    <% if @clocking_out
         user_clock_in_message = "Alter your original clock in time if you want:"
       else
         user_clock_in_message = "Clock in time:"
       end %>

    <h3>1. <%= user_clock_in_message %> </h3>
    <input id='use_current_time' type="checkbox" onclick="toggle_hidden('#datetime_select', '#use_current', '#use_current_time')"> Use current time to clock IN
    <br>

    <%= hidden_field_tag 'use_current', 'true' %>

    <div id='datetime_select' class="field">
      <%= f.label :in %>
      <br/>
      <%= f.datetime_select :in %>
    </div>
    <br/>

    <% if @clock_time.out.present? || @clocking_out %>
        <h3>2. Clock out time:</h3>

        <input id='use_current_time_out' type="checkbox" onclick="toggle_hidden('#datetime_select_out', '#use_current_out', '#use_current_time_out')"> Use current time to clock OUT

        <%= hidden_field_tag 'use_current_out', 'false' %>

        <div id='datetime_select_out' class="field">
          <%= f.label :out %>
          <br/>
          <%= f.datetime_select :out, :default => Time.now %>
        </div>
    <% end %>
    <h3>3. Update by clicking below</h3>
    <div class="actions">
      <%= f.submit :value => "Clock in", :id => "submit" %>
    </div>
<% end %>

app/views/clock_times/create.js.erb
$("#all_clock_times").append("<div class='new_clock_time'><%= escape_javascript("#{render :partial => 'users/display_clock_time', :locals => {:clock_time => @clock_time}}").html_safe %></div>");
//bind_clock_time_delete_animation(jQuery( '.delete_clock_time' ));
//$('.new_clock_time').find('a.delete_clock_time').html("test");

$('.delete_clock_time').bind('click', function() {
    $(this).closest('div').fadeOut();
});

app/views/clock_times/edit.html.erb
<h1>Editing your time</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @clock_time] %> |
<%= link_to 'Back', @user %>

app/views/clock_times/index.html.erb
<h1>Listing clock_times</h1>

<table>
  <tr>
    <th>In</th>
    <th>Out</th>
    <th>Day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clock_times.each do |clock_time| %>
  <tr>
    <td><%= clock_time.in %></td>
    <td><%= clock_time.out %></td>
    <td><%= clock_time.day %></td>
    <td><%= link_to 'Show', clock_time %></td>
    <td><%= link_to 'Edit', edit_clock_time_path(clock_time) %></td>
    <td><%= link_to 'Destroy', clock_time, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clock time', new_clock_time_path %>

app/views/clock_times/new.html.erb
<h1>Clocking in</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/clock_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>In:</b>
  <%= @clock_time.in %>
</p>

<p>
  <b>Out:</b>
  <%= @clock_time.out %>
</p>


<%= link_to 'Edit', edit_clock_time_path(@clock_time) %> |
<%= link_to 'Back', clock_times_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClockIn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.21/themes/base/jquery-ui.css" type="text/css" media="all">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_display_clock_time.html.erb
<% if !clock_time.in.nil? %>
    <div class="clock_time">
      <% if @user.clock_times.last == clock_time %>
          <br/>
          <br/>

          <h2>Most recent clock in:</h2>
          <br/>
      <% end %>

      <%
         if clock_time.out.present?
           clock_time_diff = Time.at(clock_time.out.to_time - clock_time.in.to_time).utc
         else
           clock_time_diff = nil
         end
      %>

      Time worked on <%= clock_time.in.strftime("%A") %>:
      <span class="red"> <%= clock_time_diff.nil? ? nil : clock_time_diff.strftime("%H:%M") %> </span>

      <h3>In: <%= clock_time.in.strftime("%H:%M") %></h3>
      <% if clock_time.out.nil? %>
          <% @currently_working = clock_time %>
      <% else %>
          <h3>Out: <%= clock_time.out.strftime("%H:%M") %></h3>
      <% end %>
      <%= link_to 'Delete Clock In', [@user, clock_time], confirm: 'Are you sure?', method: :delete, remote: true, class: 'delete_clock_time' %>
      |
      <%= link_to 'Edit', edit_user_clock_time_path(@user, clock_time) %>
      <br/>-------------------------<br/>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_input_popup.html.erb
<script>
    $(function() {

        var in_1i = $( "#clock_time_in_1i" ),
                out_1i = $( "#clock_time_out_1i" ),
                allFields = $( [] ).add( in_1i ).add( out_1i ),
                tips = $( ".validateTips" );

        function updateTips( t ) {
            tips
                    .text( t )
                    .addClass( "ui-state-highlight" );
            setTimeout(function() {
                tips.removeClass( "ui-state-highlight", 1500 );
            }, 500 );
        }

        function checkLength( o, n, min, max ) {
            if ( o.val().length > max || o.val().length < min ) {
                o.addClass( "ui-state-error" );
                updateTips( "Length of " + n + " must be between " +
                        min + " and " + max + "." );
                return false;
            } else {
                return true;
            }
        }

        function checkRegexp( o, regexp, validateTip ) {
            if ( !( regexp.test( o.val() ) ) ) {
                o.addClass( "ui-state-error" );
                updateTips( validateTip );
                return false;
            } else {
                return true;
            }
        }

        $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 425,
            width: 400,
            modal: true,
            close: function() {
                allFields.val( "" ).removeClass( "ui-state-error" );
            }
        });

        $( "#create-user" )
                .button()
                .click(function() {
                    $( "#dialog-form" ).dialog( "open" );
                    bind_dialog_form_close($( "#dialog-form" ));
                });
    });
</script>



<div class="demo">

  <div id="dialog-form" title="Create new clock time">
    <p class="validateTips">All form fields are required.</p>

    <%= render 'clock_times/form' %>
  </div>

  <button id="create-user">Create new Clock Time</button>
    </div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>


<% if (@users.empty?) %>
    Sorry, no users yet.  Please add a few.
    <br />
<% else %>
<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.password %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Delete User', user, confirm: 'Are you sure?', :method => :delete, :remote => true, :class => 'delete_user' %></td>
          </tr>
      <% end %>
      </table>
  <% end %>

  <br/>

  <%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<h2>Previous clock ins:</h2>
<div id="all_clock_times">
  <%
     @currently_working = nil
     count_of_weeks = 1

  %>
  <% for clock_time_week in @clock_times_by_week.values %>
        <div id="week<%= count_of_weeks %>" class="week_wrapper">
        <b>Clock Times for week #<%= count_of_weeks %></b>

        <% for clock_time in clock_time_week %>
            <%= render :partial => 'display_clock_time',
                     :locals => {:clock_time => clock_time} %>
        <% end %>

        <% count_of_weeks+=1 %>
        </div>
  <% end %>

  <a href="#" onclick="show_all_weeks();">Show All Weeks</a> <br/> <br/>
  <a href="#" onclick="hide_all_except_last_week();">Hide All Except Most Current</a>

  <script type="text/javascript">
        function hide_all_except_last_week(){
            var re = /week\d+/
            var divs=document.getElementsByTagName('div')
            for (var i=0;i<divs.length;i++){
                week_int = parseInt(divs[i].id.replace("week", ""))
              if (re.test(divs[i].id) && week_int != <%= count_of_weeks - 1 %>) {
                  divs[i].style.display = "none";
              }
            }
        }

        function show_all_weeks() {
            var re = /week\d+/
            var divs=document.getElementsByTagName('div')
            for (var i=0;i<divs.length;i++){
              if (re.test(divs[i].id) && divs[i].style.display == "none") {
                  divs[i].style.display = "block";
              }
            }
        }

        hide_all_except_last_week();
  </script>

</div>
<br/>

<% if (@currently_working.nil?) %>
    <%= link_to 'Clock in', new_user_clock_time_path(@user) %>
<% else %>
    <%= link_to 'Clock out', edit_user_clock_time_path(@user, @currently_working, :clock_out => 'true') %>
<% end %>
----------
<%= render 'input_popup' %>
----------
<br/>
<br/>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>